all:
  hosts:
    remote:
      ansible_connection: ssh
      ansible_user: ubuntu # Remote user
      ansible_host: 192.168.1.210 # Remote host
      ansible_port: 22
      ansible_ssh_private_key_file: /root/id_rsa
